import React, { memo, useCallback } from 'react';
import { Linking } from 'react-native';

import { Stack } from '@src/components/Layout/Stack';
import { ScrollView } from '@src/components/ScrollView';
import { Text } from '@src/components/Text';
import { Spacing } from '@src/utils/Spacing';

const PrivacyComponent: React.FC = () => {
  const mailToSupport = useCallback(async () => {
    try {
      Linking.openURL(`mailto:rachit.estonia@gmail.com`);
    } catch {}
  }, []);

  return (
    <ScrollView>
      <Stack pt={Spacing.large} spacing={Spacing.medium}>
        <Text>
          At MyBAN, we take your privacy very seriously. We understand the
          importance of your personal information and we are committed to
          protecting it. This privacy policy outlines the types of information
          we collect and how we use it.
        </Text>

        <Text type="medium">Information We Collect</Text>

        <Text>
          MyBAN website and app do not collect any user data at all. We do not
          require you to provide any personal information, such as your name,
          email address, or phone number, to use our website or app. We do not
          use any cookies or other tracking technologies that can identify you
          or your device.
        </Text>

        <Text type="medium">Information Usage</Text>

        <Text>
          Since we do not collect any user data, we do not use your information
          for any purpose. We do not share your information with any third
          parties or use it for any marketing or advertising activities.
        </Text>

        <Text type="medium">Data Security</Text>

        <Text>
          At MyBAN, we prioritize the security and privacy of your data. We take
          pride in informing our users that we do not collect or store any data
          on our servers or third-party servers. All data generated by our
          website and app is exclusively stored on your device and never leaves
          your device.
        </Text>

        <Text>
          This means that your personal data, financial information, and any
          other data generated on our website and app are entirely secure and
          under your control. We take all necessary measures to ensure that your
          data is safe and secure while using our website and app.
        </Text>

        <Text type="medium">Changes to This Policy</Text>

        <Text>
          We reserve the right to modify this privacy policy at any time without
          prior notice. Any changes we make will be effective immediately upon
          posting on our website. By continuing to use our website or app after
          any changes are made, you agree to be bound by the revised privacy
          policy.
        </Text>

        <Text type="medium">Contact Us</Text>

        <Text>
          If you have any questions or concerns about this privacy policy,
          please contact us at{' '}
          <Text color="blue500" onPress={mailToSupport}>
            rachit.estonia@gmail.com
          </Text>
          . We will do our best to address your concerns as quickly as possible.
        </Text>
      </Stack>
    </ScrollView>
  );
};

export const Privacy = memo(PrivacyComponent);
